name: Web App Deployemnt - Compliant
on: [push]

jobs:
  build:
    name: Web App Deployemnt - Compliant
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: workflow

      - name: Login to Azure
        uses: azure/login@v1.1
        with:
         creds: ${{secrets.AZ_SPN_CREDS}}
      
      - name: policy-compliance-scan
        uses: Azure/policy-compliance-scan@v0
        with:
          scopes: |
            
            
            
            

